version: "3"

networks:
  traefik-net:
    external: true

  mahdibaghbani-nginx:
    image: "nginx:1.25.4"
    container_name: mahdibaghbani-nginx
    restart: "unless-stopped"
    security_opt:
      - no-new-privileges:true
    networks:
      traefik-net:
        ipv4_address: 172.16.2.1
    environment:
      SERVER_NAME: "mahdibaghbani.dev"
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "${PWD}/mahdibaghbani.dev-volumes/nginx/templates/mahdibaghbani.dev.conf:/etc/nginx/templates/mahdibaghbani.dev.conf.template:ro"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-net"
      - "traefik.http.routers.mahdibaghbani-nginx.entrypoints=websecure"
      - "traefik.http.routers.mahdibaghbani-nginx.rule=Host(`mahdibaghbani.dev`, `www.mahdibaghbani.dev`)"
      - "traefik.http.routers.mahdibaghbani-nginx.service=mahdibaghbani-nginx"
      - "traefik.http.services.mahdibaghbani-nginx.loadbalancer.server.port=80"
